name: Death-Swap
main: Britt\DeathSwap\Main
description: "Death Swap By Britt"
version: 1.12.0
author: HydroGamesTeam
api:
- 3.0.0
- 4.0.0
- 3.12.0
- 3.14.0
website: https://github.com/HydroGames-dev
permissions:
  ds.cmd:
    description: Permission to all DeathSwap commands
    default: op